### ISSUE TITLE
asli_calc: 'asli' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by thomaszwagerman** [davidwyld/amundsen-sea-low-index#5]
When running `asli_calc -o something.csv` (also see #4), returns the following error:
```
Traceback (most recent call last):
  File "/gws/nopw/j04/dit/users/thozwa/venv/bin/asli_calc", line 8, in <module>
    sys.exit(asli.main())
             ^^^^^^^^^^^
  File "/gws/nopw/j04/dit/users/thozwa/venv/lib/python3.11/site-packages/asli/asli.py", line 381, in main
    a.to_csv(args.output)
  File "/gws/nopw/j04/dit/users/thozwa/venv/lib/python3.11/site-packages/asli/asli.py", line 291, in to_csv
    env = Environment(loader=PackageLoader("asli"), autoescape=select_autoescape())
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/gws/nopw/j04/dit/users/thozwa/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 326, in __init__
    raise ValueError(
ValueError: The 'asli' package was not installed in a way that PackageLoader understands.
```
`PackageLoader()` is from the jinja2 module

Going off [`PackageLoader()` docs](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader), perhaps specifying `/templates` would be a solution: `loader = PackageLoader("asli", "templates")`

**Comment by davidwyld** [comment]
Sorted.
